
# This is a basic workflow to help you get started with Actions

name: CI - Build and push Docker image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: spring-security-passkey-jhipster

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(toJson(github), 'build image')
    name: Build Jar/Docker Image and Publish to DockerHub

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK
      - name: JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image using jib:dockerBuild
      - name: Build Service using jib:dockerBuild
        run: |
           mvn package -Pprod verify jib:build -Djib.to.image=fielcapao/spring-security-passkey-jhipster:latest
#           mvn package -Pprod verify -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn jib:dockerBuild

     # Push Image for multi arch
#      - name: Push Image(amd64/arm64)
#        id: docker_build
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            fielcapao/spring-security-passkey-jhipster:latest

#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
